packages:
  - 'remote-ui'

patchedDependencies:
  'react-native-tvos@0.81.5-1': patches/react-native-tvos.patch
  '@legendapp/list@3.0.0-beta.44': patches/@legendapp__list@3.0.0-beta.44.patch

onlyBuiltDependencies:
  - 'better-sqlite3'
  - 'react-native-video'

  - 'lefthook'
